apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-reaper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # used to exclude pod-reaper so it does not reap itself (optional)
        pod-reaper: disabled
    spec:
      # this configures three different pod-reapers in one pod, each with their own criteria for reaping; if one
      # pod-reaper decides to reap a pod, the pod will be deleted
      containers:
      - name: chaos-after-2min
        image: target/pod-reaper:latest
        imagePullPolicy: Never # set to never for local minikube testing
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
        # this configuration looks at all pods in the "default" namespace without the label pod-reaper: disabled and
        # will delete 30% of found pods that have been running for more than 2 minutes
        env:
          # Set log level to Debug
          - name: LOG_LEVEL
            value: Debug
          # only look for pods in the "default" namespace
          - name: NAMESPACE
            value: default
          # run every 30 seconds
          - name: SCHEDULE
            value: "@every 30s"
          # exclude pods with metadata label pod-reaper: disabled
          - name: EXCLUDE_LABEL_KEY
            value: pod-reaper
          - name: EXCLUDE_LABEL_VALUES
            value: disabled
          # flag pods that have been alive for more than 2 minutes
          - name: MAX_DURATION
            value: 2m
          # randomly flag 30% of pods whenever they are checked
          - name: CHAOS_CHANCE
            value: ".3"
      - name: chaos
        image: target/pod-reaper:latest
        imagePullPolicy: Never # set to never for local minikube testing
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
        # this configuration looks at all pods, in every namespace every 15 seconds, and deletes 5% of them.
        env:
          # Set log level to Debug
          - name: LOG_LEVEL
            value: Debug
          # check pods every 15 seconds
          - name: SCHEDULE
            value: "0/15 * * * * *"
          # randomly flag 5% of pods whenever they are checked
          - name: CHAOS_CHANCE
            value: ".05"
      - name: error
        image: target/pod-reaper:latest
        imagePullPolicy: Never # set to never for local minikube testing
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
        # this configuration looks at all pods, in every namespace every 3 minutes and deletes any with a container
        # with status of Error or ErrImagePull
        env:
          # Set log level to Debug
          - name: LOG_LEVEL
            value: Debug
          # check pods every 3 min
          - name: SCHEDULE
            value: "@every 3m"
          # randomly flag 5% of pods whenever they are checked
          - name: CONTAINER_STATUSES
            value: "Error,ErrImagePull,ImagePullBackOff"
